github:
  is_project_page: false
google_analytics: G-5V7QQRNGXT
last_updated: Tuesday, July 15, 2025
markdown: kramdown
name: ''
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
title: iRacing League Directory
