markdown: kramdown
name: ""
title: "iRacing League Directory"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: G-5V7QQRNGXT
github:
  is_project_page: false
